### ISSUE TITLE
Review and merge all upstream's pull requests

### ISSUE THREAD

**Issue by omissis** [omissis/go-jsonschema-fork#3]
**List of PRs**

- [x] atombender/go-jsonschema#47 
  - #2 
- [x] atombender/go-jsonschema#45
  - #4
- [x] atombender/go-jsonschema#43
  - #6
- [x] atombender/go-jsonschema#40
  - #1 
- [x] atombender/go-jsonschema#39
  - #7
- [ ] atombender/go-jsonschema#38
  - TODO
- [x] atombender/go-jsonschema#23
  - #14
- [ ] atombender/go-jsonschema#21
  - TODO
- [ ] atombender/go-jsonschema#10
  - TODO

**Comment by scop** [comment]
> * [ ]  [feat: primitive validation atombender/go-jsonschema#21](https://github.com/atombender/go-jsonschema/pull/21)
>   * TODO

Forward ported here as https://github.com/omissis/go-jsonschema/pull/17

**Comment by atombender** [comment]
Hi, I see you started this fork. Want to take over as maintainer? I'm not using go-jsonschema these days and don't really have time to maintain it.

**Comment by omissis** [comment]
Hey @atombender , I'd be glad to!

**Comment by atombender** [comment]
@omissis Sorry I've been late to address this. Still interested? Do you have a handle on other forks that have made changes you might want to pull in?

**Comment by omissis** [comment]
Hey @atombender, I haven't looked at new PRs this year so the status is still the one describe above in the issue description, but I will do one more round soon to ensure everything of interest has been included. Besides that yes, I am still interested. I will probably explore subschemas soon, and possibly look into validation later on this year: we're actively using the binary within our kubernetes distribution (https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/Makefile#L4) so it would be cool to get the chance to maintain it. any preference on how to proceed?

**Comment by atombender** [comment]
Cool! I could transfer my repo to you, but you already have a fork, and I don't think GitHub has a way to make another fork the "main" repo? Otherwise I could just put a link in the readme and archive my repo.

**Comment by shanduur** [comment]
Great to see a work done on a fork! I think the archive and add a URL to @omissis fork is best way of handling this.

**Comment by omissis** [comment]
I think transferring the repository could be a bit better in terms of handling redirects, but I am not 100% sure that would suffice in order to keep the go module name unchanged and avoid disrupting downstream users of the library: I need to do a bit of research on the topic before deciding if it's a good idea.
Otherwise we can simply point to my repository from atombender's and have the users update their references: that would work for me, too.

**Comment by shanduur** [comment]
@omissis @atombender any updates? If help is needed, I'm here 😄

**Comment by omissis** [comment]
hey 👋 no updates, I just need to look into the matter :)

**Comment by omissis** [comment]
hi @atombender! I finally took the time to run some tests to ensure the transfer won't cause disruption to downstream users and I would go with repository transfer. I already renamed this one to allow the move, so I am ready when you are :)

**Comment by omissis** [comment]
For future reference: github repository transfer and go mod do handle everything transparently, so the users will keep receiving updates when referencing github.com/atombender/go-jsonschema even if the changes happen here. I might be changing the module name in a future release to avoid confusion, but I'll plan that further down the road.

**Comment by atombender** [comment]
Great! I tried transferring, but GitHub fails with:

> omissis already has a repository in the atombender/go-jsonschema network

I wonder if it's possible for you to "unfork" the repo somehow?

**Comment by omissis** [comment]
ok @atombender I sent a support request to detach the fork, hopefully it's going to be processed soon enough

**Comment by omissis** [comment]
hi @atombender they detached this repo, can you try again? thanks! 🙏

**Comment by atombender** [comment]
Done!

**Comment by omissis** [comment]
Awesome! 🚀  Thank you for taking the time and for having put in the work to start this repo! ❤️

**Comment by omissis** [comment]
closing this is issue, as the conversation moved to the original repo: https://github.com/omissis/go-jsonschema/issues/53
